net.sf.jasperreports.extension.registry.factory.fonts=net.sf.jasperreports.engine.fonts.SimpleFontExtensionsRegistryFactory
net.sf.jasperreports.extension.simple.font.families.firaSans=no/kartverket/jasperreports/firaSans.xml
net.sf.jasperreports.extension.simple.font.families.mulish=no/kartverket/jasperreports/mulish.xml
